# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Bill.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Bill(object):
    def setupUi(self, Bill):
        Bill.setObjectName("Bill")
        Bill.resize(1024, 600)
        self.label = QtWidgets.QLabel(Bill)
        self.label.setGeometry(QtCore.QRect(400, 20, 250, 35))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Bill)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 100, 200, 25))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelSaleID = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelSaleID.setObjectName("labelSaleID")
        self.horizontalLayout.addWidget(self.labelSaleID)
        self.lineEditSaleID = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditSaleID.setObjectName("lineEditSaleID")
        self.horizontalLayout.addWidget(self.lineEditSaleID)
        self.dateTimeEditBill = QtWidgets.QDateTimeEdit(Bill)
        self.dateTimeEditBill.setGeometry(QtCore.QRect(50, 70, 200, 25))
        self.dateTimeEditBill.setObjectName("dateTimeEditBill")
        self.tableWidgetBill = QtWidgets.QTableWidget(Bill)
        self.tableWidgetBill.setGeometry(QtCore.QRect(210, 150, 610, 350))
        self.tableWidgetBill.setObjectName("tableWidgetBill")
        self.tableWidgetBill.setColumnCount(4)
        self.tableWidgetBill.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBill.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBill.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBill.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBill.setHorizontalHeaderItem(3, item)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Bill)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(550, 520, 260, 35))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelGrandTotal = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelGrandTotal.setObjectName("labelGrandTotal")
        self.horizontalLayout_2.addWidget(self.labelGrandTotal)
        self.lineEditGrandTotal = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEditGrandTotal.setObjectName("lineEditGrandTotal")
        self.horizontalLayout_2.addWidget(self.lineEditGrandTotal)
        self.labelBath = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelBath.setObjectName("labelBath")
        self.horizontalLayout_2.addWidget(self.labelBath)

        self.retranslateUi(Bill)
        QtCore.QMetaObject.connectSlotsByName(Bill)

    def retranslateUi(self, Bill):
        _translate = QtCore.QCoreApplication.translate
        Bill.setWindowTitle(_translate("Bill", "Bill"))
        self.label.setText(_translate("Bill", "Kiosk Payment"))
        self.labelSaleID.setText(_translate("Bill", "Sale ID"))
        item = self.tableWidgetBill.horizontalHeaderItem(0)
        item.setText(_translate("Bill", "Product List"))
        item = self.tableWidgetBill.horizontalHeaderItem(1)
        item.setText(_translate("Bill", "Number"))
        item = self.tableWidgetBill.horizontalHeaderItem(2)
        item.setText(_translate("Bill", "Price"))
        item = self.tableWidgetBill.horizontalHeaderItem(3)
        item.setText(_translate("Bill", "Total"))
        self.labelGrandTotal.setText(_translate("Bill", "Grand Total "))
        self.labelBath.setText(_translate("Bill", " Bath"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Bill = QtWidgets.QWidget()
    ui = Ui_Bill()
    ui.setupUi(Bill)
    Bill.show()
    sys.exit(app.exec_())
