# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_product.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from re import S
from sqlite3.dbapi2 import Connection, connect
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtSql import QSqlQuery
import mysql.connector as mc
import mysql.connector as md
from os import name
import sqlite3
import ast

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 600)
        self.labelImage = QtWidgets.QLabel(Form)
        self.labelImage.setGeometry(QtCore.QRect(0, 0, 1031, 601))
        self.labelImage.setText("")
        self.labelImage.setPixmap(QtGui.QPixmap("D:/Project/image/data2.png"))
        self.labelImage.setObjectName("labelImage")
        self.labelBarcode = QtWidgets.QLabel(Form)
        self.labelBarcode.setGeometry(QtCore.QRect(80, 110, 75, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelBarcode.setFont(font)
        self.labelBarcode.setObjectName("labelBarcode")
        self.labelProductName = QtWidgets.QLabel(Form)
        self.labelProductName.setGeometry(QtCore.QRect(80, 150, 150, 20))
        self.labelProductName.setFont(font)
        self.labelProductName.setObjectName("labelProductName")
        self.labelPrice = QtWidgets.QLabel(Form)
        self.labelPrice.setGeometry(QtCore.QRect(80, 190, 95, 20))
        self.labelPrice.setFont(font)
        self.labelPrice.setObjectName("labelPrice")
        self.lineEditBarcode = QtWidgets.QLineEdit(Form)
        self.lineEditBarcode.setGeometry(QtCore.QRect(220, 110, 180, 25))
        self.lineEditBarcode.setFont(font)
        self.lineEditBarcode.setObjectName("lineEditBarcode")
        self.lineEditProductName = QtWidgets.QLineEdit(Form)
        self.lineEditProductName.setGeometry(QtCore.QRect(220, 150, 180, 25))
        self.lineEditProductName.setFont(font)
        self.lineEditProductName.setObjectName("lineEditProductName")
        self.lineEditPrice = QtWidgets.QLineEdit(Form)
        self.lineEditPrice.setGeometry(QtCore.QRect(220, 190, 180, 25))
        self.lineEditPrice.setFont(font)
        self.lineEditPrice.setObjectName("lineEditPrice")
        self.pushButtonSave = QtWidgets.QPushButton(Form)
        self.pushButtonSave.setGeometry(QtCore.QRect(120, 250, 100, 30))
        self.pushButtonSave.setFont(font)
        self.pushButtonSave.setStyleSheet("background-color:white;\n"
                                                "color:black;\n"
                                                "border-style:outset;\n"
                                                "border-width:1px;\n"
                                                "border-radius:2px;\n"
                                                "border-color:gray;")
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.pushButtonSave.clicked.connect(self.insert_data)
        self.pushButtonClear = QtWidgets.QPushButton(Form)
        self.pushButtonClear.setGeometry(QtCore.QRect(260, 250, 100, 30))
        self.pushButtonClear.setFont(font)
        self.pushButtonClear.setStyleSheet("background-color:white;\n"
                                                "color:black;\n"
                                                "border-style:outset;\n"
                                                "border-width:1px;\n"
                                                "border-radius:2px;\n"
                                                "border-color:gray;")
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.tableWidgetProductList = QtWidgets.QTableWidget(Form)
        self.tableWidgetProductList.setGeometry(QtCore.QRect(485, 110, 455, 350))
        self.tableWidgetProductList.setFont(font)
        self.tableWidgetProductList.setObjectName("tableWidgetProductList")
        self.tableWidgetProductList.setColumnCount(3)
        self.tableWidgetProductList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProductList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProductList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProductList.setHorizontalHeaderItem(2, item)
        self.tableWidgetProductList.setHorizontalHeaderLabels(["Barcode", "Product Name", "Price"])
        self.loaddate
        self.labelAddProduct = QtWidgets.QLabel(Form)
        self.labelAddProduct.setGeometry(QtCore.QRect(180, 40, 150, 30))
        self.labelAddProduct.setFont(font)
        self.labelAddProduct.setObjectName("labelAddProduct")
        self.labelProductList = QtWidgets.QLabel(Form)
        self.labelProductList.setGeometry(QtCore.QRect(660, 40, 150, 30))
        self.labelProductList.setFont(font)
        self.labelProductList.setObjectName("labelProductList")
        self.pushButtonEdit = QtWidgets.QPushButton(Form)
        self.pushButtonEdit.setGeometry(QtCore.QRect(580, 500, 100, 30))
        self.pushButtonEdit.setFont(font)
        self.pushButtonEdit.setStyleSheet("background-color:white;\n"
                                                "color:black;\n"
                                                "border-style:outset;\n"
                                                "border-width:1px;\n"
                                                "border-radius:2px;\n"
                                                "border-color:gray;")
        self.pushButtonEdit.setObjectName("pushButtonEdit")
        self.pushButtonEdit.clicked.connect(self.pushButtonEdit1)
        self.pushButtonDelete = QtWidgets.QPushButton(Form)
        self.pushButtonDelete.setGeometry(QtCore.QRect(760, 500, 100, 30))
        self.pushButtonDelete.setFont(font)
        self.pushButtonDelete.setStyleSheet("background-color:white;\n"
                                                "color:black;\n"
                                                "border-style:outset;\n"
                                                "border-width:1px;\n"
                                                "border-radius:2px;\n"
                                                "border-color:gray;")
        self.pushButtonDelete.setObjectName("pushButtonDelete")

        self.pushButtonBack = QtWidgets.QPushButton(Form)
        self.pushButtonBack.setGeometry(QtCore.QRect(10, 560, 100, 30))
        self.pushButtonBack.setFont(font)
        self.pushButtonBack.setStyleSheet("background-color:gray;\n"
                                                "color:white;\n"
                                                "border-style:outset;\n"
                                                "border-width:2px;\n"
                                                "border-radius:2px;\n"
                                                "border-color:black;")
        self.pushButtonBack.setObjectName("pushButtonBack")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def loaddate(self):
        connection = md.connect(host="localhost",
            user="root",
            password="",
            database="project")
        cur = connection.cursor()
        cur.execute("SELECT * FROM product")

        self.tableWidgetProductList.setRowCount(50)
        tablerow = 0
        for row in cur.execute("SELECT * FROM product"):
            self.tableWidgetProductList.setItem(tablerow, 0, QtWidgets.QTableWidgetItem(row[0]))
            self.tableWidgetProductList.setItem(tablerow, 1, QtWidgets.QTableWidgetItem(row[1]))
            self.tableWidgetProductList.setItem(tablerow, 2, QtWidgets.QTableWidgetItem(row[2]))

            tablerow +=1
    def insert_data(self):
        mydb = mc.connect(
            host="localhost",
            user="root",
            password="",
            database="project"
        )
        mycursor = mydb.cursor()

        barcode = self.lineEditBarcode.text()
        product_name = self.lineEditProductName.text()
        price = self.lineEditPrice.text()

        sqla = "INSERT INTO product (barcode, product_name, price) VALUES (%s, %s, %s)"
        val = (barcode, product_name, price)

        mycursor.execute(sqla, val)
        mydb.commit()

    def getrowcowcount(self):
        query = QSqlQuery()
        query.exec_("SELECT * FROM product")
        query.next()
        rowcount = query.value()
        return rowcount

    def pushButtonEdit1(self):
        self.tableWidgetProductList.clear()
        self.tableWidgetProductList.setRowCount(self.getrowcount())
        self.tableWidgetProductList.setRowCount(1)
        self.tableWidgetProductList.setRowCount(1000)
        columnheaders = ["Barcode", "Product", "Price"]
        self.tableWidgetProductList.setHorizontalHeaderLabels(columnheaders)
        db = mc.connect(
            host="localhost",
            user="root",
            password="",
            database="project"
        )
        query = db.cursor()

        query.execute('''SELECT * FROM product''')
        for index , form in enumerate(query.fetchall()):
            i = 0
            for item in form:
                # print(str(item))
                self.tableWidgetProductList.setItem(index, i, QtWidgets.QTableWidgetItem(str(item)))       
                i = i + 1
            self.tableWidgetProductList.insertRow(1000)
    

       
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Add Product"))
        self.labelBarcode.setText(_translate("Form", "Barcode"))
        self.labelProductName.setText(_translate("Form", "Product Name"))
        self.labelPrice.setText(_translate("Form", "Price"))
        self.pushButtonSave.setText(_translate("Form", "Save"))
        self.pushButtonClear.setText(_translate("Form", "Clear"))
        item = self.tableWidgetProductList.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Barcode"))
        item = self.tableWidgetProductList.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Product Name"))
        item = self.tableWidgetProductList.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Price"))
        self.labelAddProduct.setText(_translate("Form", "Add Product"))
        self.labelProductList.setText(_translate("Form", "Product List"))
        self.pushButtonEdit.setText(_translate("Form", "Refresh"))
        self.pushButtonDelete.setText(_translate("Form", "Delete"))
        self.pushButtonBack.setText(_translate("Form", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
