# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from typing import MutableMapping
from PyQt5 import QtCore, QtGui, QtWidgets
from product_user import Ui_Form1

class Ui_Form(object):

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 600)
        self.labelImage = QtWidgets.QLabel(Form)
        self.labelImage.setGeometry(QtCore.QRect(0, 0, 1031, 601))
        self.labelImage.setText("")
        self.labelImage.setPixmap(QtGui.QPixmap("D:/Project/image/main2.png"))
        self.labelImage.setObjectName("labelImage")
        self.pushButtonProductScan = QtWidgets.QPushButton(Form)
        self.pushButtonProductScan.setGeometry(QtCore.QRect(350, 415, 300, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonProductScan.setFont(font)
        self.pushButtonProductScan.setStyleSheet("background-color:white;\n"
                                            "color:black;\n"
                                            "border-style:outset;\n"
                                            "border-width:1px;\n"
                                            "border-radius:10px;\n"
                                            "border-color:black;")
        self.pushButtonProductScan.setObjectName("pushButtonStaff")
        self.pushButtonProductScan.clicked.connect(self.product_userscr)
        # self.pushButtonCustomer = QtWidgets.QPushButton(Form)
        # self.pushButtonCustomer.setGeometry(QtCore.QRect(360, 450, 301, 81))
        # font = QtGui.QFont()
        # font.setPointSize(20)
        # font.setBold(True)
        # font.setWeight(75)
        # self.pushButtonCustomer.setFont(font)
        # self.pushButtonCustomer.setStyleSheet("background-color:white;\n"
        #                                         "color:black;\n"
        #                                         "border-style:outset;\n"
        #                                         "border-width:1px;\n"
        #                                         "border-radius:10px;\n"
        #                                         "border-color:black;")
        # self.pushButtonCustomer.setObjectName("pushButtonCustomer")
        # self.pushButtonCustomer.clicked.connect(self.product_userscr)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def product_userscr(self):
        self.Form1 = QtWidgets.QWidget()
        self.ui = Ui_Form1()
        self.ui.setupUi(self.Form1)
        self.Form1.show()

    # def data_product(self):
    #     self.Form2 = QtWidgets.QWidget()
    #     self.ui = Ui_Form2()
    #     self.ui.setupUi(self.Form2)
    #     self.Form2.show()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Main"))
        self.pushButtonProductScan.setText(_translate("Form", "Product Scan"))
        # self.pushButtonCustomer.setText(_translate("Form", "CUSTOMER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
